### ISSUE TITLE
Enforce formatting

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-seatbelt#7]
When I run `forge fmt`, the formatting of all files is changed

_Originally posted by @Rubilmax in https://github.com/morpho-org/morpho-seatbelt/pull/4#pullrequestreview-1435936363_

**Comment by Tristan22400** [comment]
I think we can close this issue as I run foundryup and forge fmt. But nothing changes on my part. Can you check if it is still the case @MerlinEgalite?

**Comment by MerlinEgalite** [comment]
Yes but someone can wrongly format and push, so I think we should automate this on commit for instance. You can check what @Rubilmax did in other repos
